---
language: python
sudo: required

install:
  - pip install ansible

script:
  # Check the roles syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
